apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: dynakube
  namespace: dynatrace
spec:
  oneAgent:
    useCSIDriver: true
  apiUrl: https://${dynatrace_url}.live.dynatrace.com/api
  skipCertCheck: true
