apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: dynakube
  namespace: dynatrace
spec:
  oneAgent:
    useCSIDriver: true
  apiUrl: ${{ secrets.DYNATRACE_SERVER }}/api
  skipCertCheck: true
