name: Destroy Infra

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GKE_CLUSTER: gke-cluster
      GKE_ZONE: us-central1-a

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Init Terraform
      working-directory: lab8-git-actions-gke/infra
      run: terraform init -input=false

    - name: Plan Destroy
      working-directory: lab8-git-actions-gke/infra
      run: terraform plan -destroy

    - name: Terraform Destroy
      working-directory: lab8-git-actions-gke/infra
      run: terraform destroy -auto-approve
