name: Destroy Infra

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GKE_CLUSTER: gke-cluster
      GKE_ZONE: us-central1-a

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up GCP
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Set GOOGLE_APPLICATION_CREDENTIALS
      run: |
        echo '${{ secrets.GCP_SA_KEY }}' > $HOME/gcp-key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp-key.json" >> $GITHUB_ENV

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Terraform Destroy
      working-directory: lab8-git-actions-gke/infra
      run: terraform destroy -auto-approve
