name: Destroy Infra

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GKE_CLUSTER: gke-cluster
      GKE_ZONE: us-central1-a

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Write backend.tf dynamically
      working-directory: lab8-git-actions-gke/infra
      run: |
        export BUCKET_NAME=tf-state-${{ secrets.GCP_PROJECT_ID }}-${{ github.event.workflow_run.id }}
        echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV
        cat <<EOF > backend.tf
        terraform {
          backend "gcs" {
            bucket  = "$BUCKET_NAME"
            prefix  = "terraform/state"
          }
        }
        EOF

    - name: Terraform Destroy
      working-directory: lab8-git-actions-gke/infra
      run: terraform destroy -auto-approve

    - name: Delete GCS bucket
      run: |
        gsutil -m rm -r gs://$BUCKET_NAME


    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Init Terraform
      working-directory: lab8-git-actions-gke/infra
      run: terraform init -input=false

    - name: Plan Destroy
      working-directory: lab8-git-actions-gke/infra
      run: terraform plan -destroy

    - name: Terraform Destroy
      working-directory: lab8-git-actions-gke/infra
      run: terraform destroy -auto-approve
